In [174]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'./data/book_douban.csv', index_col = 0)  # index_col=0 把第一列作为行索引
df.head()

,书名,作者,出版社,出版时间,数,价格,ISBM,评分,评论数量
1,中国武侠小说史论,叶洪生,NaN,1900,NaN,NaN,9.790000e+12,0.0,NaN
2,How to cook and eat in Chinese,杨步伟,The John Day company,1945,262,NaN,9.780000e+12,0.0,NaN
3,吐鲁番考古记,黄文弼,中国科学院出版社,1954,208,NaN,NaN,0.0,NaN
4,塞瓦斯托波尔故事,列夫·托尔斯泰,新文艺出版社,1955,172,NaN,NaN,0.0,NaN
5,敦煌变文集（上下集）,王重民,人民文学出版社,1957,922,NaN,NaN,0.0,NaN

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60626 entries, 1 to 60670
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   书名      60626 non-null  object
 1   作者      59612 non-null  object
 2   出版社     57908 non-null  object
 3   出版时间    59634 non-null  object
 4   数       56369 non-null  object
 5   价格      58777 non-null  object
 6   ISBM    59539 non-null  float64
 7   评分      60626 non-null  float64
 8   评论数量    53971 non-null  float64
dtypes: float64(3), object(6)
memory usage: 4.6+ MB

In [220]:
data1 = df.copy()
data1 = data1.rename(columns = {'数':'页数'})
data1.reset_index(drop = True, inplace = True)
data1.head(10)
# print(data1.columns.tolist())

,书名,作者,出版社,出版时间,页数,价格,ISBM,评分,评论数量
0,中国武侠小说史论,叶洪生,NaN,1900,NaN,NaN,9.790000e+12,0.0,NaN
1,How to cook and eat in Chinese,杨步伟,The John Day company,1945,262,NaN,9.780000e+12,0.0,NaN
2,吐鲁番考古记,黄文弼,中国科学院出版社,1954,208,NaN,NaN,0.0,NaN
3,塞瓦斯托波尔故事,列夫·托尔斯泰,新文艺出版社,1955,172,NaN,NaN,0.0,NaN
4,敦煌变文集（上下集）,王重民,人民文学出版社,1957,922,NaN,NaN,0.0,NaN
5,可笑的女才子,[法] 莫里哀,作家出版社,1957,96,NaN,NaN,0.0,NaN
6,鲁迅传,石一歌,上海人民出版社,1976,148,NaN,NaN,0.0,NaN
7,中國邊疆民族與環太平洋文化,凌純聲,聯經出版事業股份有限公司,1979,NaN,NaN,9.790000e+12,0.0,NaN
8,两面间谍,约翰·马斯特曼,群众出版社,1979,182,NaN,NaN,0.0,NaN
9,Lu Xun Selected Works(all 4 Volumes in slipcase),Lu Xun,Foreign Language Press,1980,NaN,NaN,9.780000e+12,0.0,NaN

In [181]:
df.shape

(60626, 9)

In [184]:
df.describe()

               ISBM            评分           评论数量
count  5.953900e+04  60626.000000   53971.000000
mean   9.789305e+12      7.164194     743.507939
std    2.542204e+09      2.616873    4112.090523
min    9.780000e+12      0.000000      10.000000
25%    9.790000e+12      7.300000      35.000000
50%    9.790000e+12      7.900000      93.000000
75%    9.790000e+12      8.500000     320.000000
max    9.790000e+12     10.000000  209602.000000

In [188]:
df.replace('NaN', np.nan, inplace = True)
df.isnull().sum()

书名         0
作者      1014
出版社     2718
出版时间     992
数       4257
价格      1849
ISBM    1087
评分         0
评论数量    6655
dtype: int64

In [190]:
print(df.columns.tolist())

['书名', '作者', '出版社', '出版时间', '数', '价格', 'ISBM', '评分', '评论数量']

In [222]:
data1 = df.copy()
data1 = data1.rename(columns = {'数':'页数'})
data1.reset_index(drop = True, inplace = True)
data1.head(10)
data1 = data1.drop(columns=['ISBM'])
data1 = data1.dropna(axis = 0,subset = ['作者','出版社','出版时间','页数','价格','评分','评论数量'], how = 'any')
data1 = data1.reset_index(drop = True)

In [223]:
data1.isnull().sum()

书名      0
作者      0
出版社     0
出版时间    0
页数      0
价格      0
评分      0
评论数量    0
dtype: int64

In [196]:
data1.shape

(47745, 8)

In [208]:
data1.drop(data1[data1['出版时间'].str.len() != 4].index, axis = 0, inplace = True)
data1 = data1[data1['出版时间'].str.isdigit()]
data1['出版时间'] = data1['出版时间'].astype(np.int32)
data1.drop(data1[data1['出版时间'] > 2022].index, inplace = True)
data1.head()

AttributeError: Can only use .str accessor with string values!

In [209]:
data1.shape

(3465, 9)

In [217]:
data1['评论数量'] = data1['评论数量'].astype(np.int32)
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47745 entries, 0 to 47744
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   书名      47745 non-null  object
 1   作者      47745 non-null  object
 2   出版社     47745 non-null  object
 3   出版时间    47745 non-null  object
 4   数       47745 non-null  object
 5   价格      47745 non-null  object
 6   评分      47745 non-null  float64
 7   评论数量    47745 non-null  int32
dtypes: float64(1), int32(1), object(6)
memory usage: 2.7+ MB

In [225]:
data1['页数'].str.contains('\.').value_counts()

页数
False    47738
True         7
Name: count, dtype: int64

In [226]:
data1['页数'] = data1['页数'].apply(lambda x:x.replace(',','').replace(' ',''))
data1.drop(data[~(data1['页数'].str.isdecimal())].index, axis = 0, inplace = True)
data1

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20084\2440319538.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data1.drop(data[~(data1['页数'].str.isdecimal())].index, axis = 0, inplace = True)

,书名,作者,出版社,出版时间,页数,价格,评分,评论数量
0,只有你聽到 Calling You,乙一,青春文化,2005,217,55,8.7,4760.0
1,安源,裴宜理 (Elizabeth J. Perry),香港大學出版社,2014/7/1,336,160,8.6,51.0
2,易卜生评论集,编辑委员会编,外语教学与研究出版社,1982/12/01,431,1.8,8.1,15.0
3,不祥的宴會,阿嘉莎·克莉絲蒂,遠景·風雲時代,30011,316,90,7.8,28.0
4,SKETCHTRAVEL速寫本的奇幻旅程,KONDO Robert,積木文化,2014/3/4,192,880,9.0,27.0
...,...,...,...,...,...,...,...,...
47740,呼吸--宇宙的毁灭,[美]特德-姜,科幻世界2009.11,2009/11,82,0,9.1,116.0
47741,大方广佛华严经,實叉難陀,上海古籍出版社,2006,2502,0,9.4,114.0
47742,佛教的精神与特色,林世敏,台湾佛教青年协会,1991,125,0,8.6,49.0
47743,名苑猎凶·庄园迷案,(英)阿加莎·克里斯蒂,内蒙古人民出版社,2003/11,531,0,6.9,25.0
47744,坦克-前进！,[德]H.古德里安,中国人民解放军装甲司令部,1982/3,260,0,7.5,17.0

In [229]:
data1['页数'] = data1['页数'].astype(str).str.extract(r'(\d+)')
data1['页数'] = data1['页数'].astype('Int32')
data1 = data1[(data1['页数'].notna()) & (data1['页数'] > 0)]
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47678 entries, 0 to 47744
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   书名      47678 non-null  object
 1   作者      47678 non-null  object
 2   出版社     47678 non-null  object
 3   出版时间    47678 non-null  object
 4   页数      47678 non-null  Int32
 5   价格      47678 non-null  object
 6   评分      47678 non-null  float64
 7   评论数量    47678 non-null  float64
dtypes: Int32(1), float64(2), object(5)
memory usage: 3.1+ MB

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20084\213865139.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['页数'] = data1['页数'].astype(str).str.extract(r'(\d+)')
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20084\213865139.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['页数'] = data1['页数'].astype('Int32')